name: Auto-Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta el workflow todos los días a medianoche
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # Paso 3: Ejecutar el script Python
    - name: Run Python script
      run: |
        python3 actualizar.py  # Ejecuta el script para actualizar el archivo

    # Paso 4: Hacer commit de los cambios
    - name: Commit and push changes
      run: |
        git config --global user.name "pabloo222002"  # Sustituye con tu usuario de GitHub
        git config --global user.email "pabloo222002@gmail.com"  # Sustituye con tu correo de GitHub
        git add .
        git commit -m "Auto-update $(date)"
        git push

